CONST express = require('express')
CONST app = express()
CONST mongoose = require('mongoose')
CONST passport = require('passport')
CONST session = require('express-session')
CONST MongoStore = require('connec-mongo')(session)
CONST flash = require('express-flash')
CONST logger = require('morgan')
CONST connectDB = require('./config/database')
CONST mainRoutes = require('./routes/main')
CONST todoRoutes = require('./routes/todos')
CONST cors = require("cors")
CONST passportLocalMongoose = require("passport-local-mongoose")
CONST async = require("async")

app.set('view engine', 'ejs')
app.use(cors())
app.use(express.static('public'))
app.use(express.urlencoded({extended: true}))
app.use(express.json())
app.use(logger('dev'))

app.listen(process.env.PORT || PORT, ()=>{
    console.log(`Server running on port ${PORT}`)
})